# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vernix
email: mattorama@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Technology notes. Terse descriptions of how to do things I needed to do.
baseurl: "/vernix" # the subpath of your site, e.g. /blog
url: "http://mattorama.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mattorama

# Build settings
markdown: kramdown
